# numpy
* https://numpy.org/numpy-tutorials/
* numpy : Numerical Python 과학적, 산업적 연산을 위한 패키지
* 다차원 배열, 행렬 연산에 주로 사용
* numpy는 python의 list와 비슷한 자료형
* 순서가 있는 자료형
* 파이썬의 list와의 차이점은 자료형이 1가지만 들어감

# 차원
* 0차원 = 점, 스칼라 a = 10 (자료가 1개)
* 1차원 = 선, 벡터, 배열, list, tuple [1,2,3,4]
    * 벡터는 방향을 가진 데이터
* 2차원 = 면, 가로, 세로, DB 테이블, Dataframe, matrix
* 3차원 = 입체, (가로, 세로, 깊이), 정육면체
    * 엑셀 시트가 여러개있는 엑셀 파일 하나는 3차원이 됨
* 4차원 = 3차원 요소가 2개 이상
    * 3차원인 엑셀 파일이 여러개있는 폴더는 4차원이 됨
* 5차원 = 4차원 요소가 2개 이상

In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
s = 10 # 스칼라

### .ndim / .shape
* ndim : 차원을 출력하는 메서드
* shape : 차원의 형태를 출력하는 메서드
* 스칼라는 둘 다 AttributeError

In [6]:
# ndarray는 벡터이므로 1차원
a.ndim

1

In [7]:
# 방향이 없는 벡터
a.shape

(5,)

In [20]:
# 열벡터
a2 =np.array([[1],[2],[3],[4],[5]])
print(a2)
print(a2.ndim)
print(a2.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
2
(5, 1)


In [21]:
# 행벡터
a3 = np.array([[1,2,3,4,5]])
print(a3)
print(a3.ndim)
print(a3.shape)

[[1 2 3 4 5]]
2
(1, 5)


In [9]:
# 2차원 데이터
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
print(c.ndim)
# (행, 열)
print(c.shape)

2
(2, 5)


In [11]:
# 3차원 데이터
d = np.array([[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]])
d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [13]:
print(d.ndim)
# (개수, 행, 열)
print(d.shape) # 2행 5열이 2개

3
(2, 2, 5)


In [14]:
# 4차원 데이터
e = np.array([[[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]],[[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]]])
e

array([[[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]],


       [[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]])

In [15]:
print(e.ndim)
# (개수, 개수, 행, 열)
print(e.shape) # 2행 5열이 2개가 2개

4
(2, 2, 2, 5)


In [16]:
# 5차원 데이터
f = np.array([[[[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]],[[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]]],[[[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]],[[[1,2,3,4,5], [6,7,8,9,10]],[[1,2,3,4,5], [6,7,8,9,10]]]]])
f

array([[[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]],



       [[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]],


        [[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]],

         [[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10]]]]])

In [17]:
print(f.ndim)
# (개수, 개수, 개수, 행, 열)
print(f.shape) # 2행 5열이 2개가 2개가 2개

5
(2, 2, 2, 2, 5)


# numpy를 사용하는 이유
* 행렬 연산이 쉽고 빠르기 때문

In [22]:
# 스칼라 연산
a = 10
b = 5
scalar = a + b
print(scalar)

15


In [23]:
scalar + 10

25

In [26]:
# 1차원 데이터 벡터의 연산
b1 = [1,2,3,4,5]
# 리스트의 요소에 10을 곱한 후 다시 리스트로 만드세요
b1_multiple = [x*10 for x in b1]
b1_multiple

[10, 20, 30, 40, 50]

In [27]:
b1_multiple = list(map(lambda x: x * 10, b1))
b1_multiple

[10, 20, 30, 40, 50]

In [30]:
# 2차원 데이터 계산 *10하기
second = np.array([[1,2,3],[1,2,3]])
print(second)
print(second.ndim)
print(second.shape)

[[1 2 3]
 [1 2 3]]
2
(2, 3)


In [35]:
second_multiple = []
for nums in second:
    temp = []
    for num in nums:
        temp.append(num*10)
    second_multiple.append(result)
np.array(second_multiple)

array([[10, 20, 30],
       [10, 20, 30]])

In [36]:
second_np_mul = second * 10
second_np_mul

array([[10, 20, 30],
       [10, 20, 30]])

# numpy에서 자주 사용하는 메서드
* .ndim : 몇 차원인지 보는 것
* .shape : 몇 차원, 몇 행, 몇 열로 되어있는지 구조 확인
* .size : 배열 안에 있는 요소의 총 개수가 몇 개인지 확인
* .dtype : 배열 안에 있는 요소의 데이터타입 확인

In [37]:
second.size

6

In [38]:
second.dtype

dtype('int64')

In [40]:
second_div = second / 2
print(second_div)
print(second_div.dtype)

[[0.5 1.  1.5]
 [0.5 1.  1.5]]
float64


# ndarray 만들기
* numpy의 기본 자료형 ndarray
* np.array(리스트/튜플)
* 자료형은 반드시 1가지만 넣는다

In [42]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

### np.arange(시작, 끝, step)

In [48]:
nums = np.arange(1,101)
nums

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### .reshape(행, 열)
* 벡터를 원하는 크기의 matrix 혹은 다차원 배열로 변환

In [49]:
print(nums.ndim)
print(nums.shape)
nums.reshape(5,20)

1
(100,)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [50]:
nums.reshape(5, 4, 5)

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10],
        [ 11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20]],

       [[ 21,  22,  23,  24,  25],
        [ 26,  27,  28,  29,  30],
        [ 31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40]],

       [[ 41,  42,  43,  44,  45],
        [ 46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60]],

       [[ 61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75],
        [ 76,  77,  78,  79,  80]],

       [[ 81,  82,  83,  84,  85],
        [ 86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100]]])

In [54]:
nums.reshape(-1, 25)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
         64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

### .flatten() : 다차원 배열을 1차원으로 펼쳐줌

In [56]:
nums.reshape(-1, 25).flatten()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

### np.flip() : 행렬의 순서를 뒤집을 때

In [57]:
np.flip(nums.reshape(-1, 25))

array([[100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
         87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76],
       [ 75,  74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,
         62,  61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 50,  49,  48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,
         37,  36,  35,  34,  33,  32,  31,  30,  29,  28,  27,  26],
       [ 25,  24,  23,  22,  21,  20,  19,  18,  17,  16,  15,  14,  13,
         12,  11,  10,   9,   8,   7,   6,   5,   4,   3,   2,   1]])

### np.linspace(시작, 끝, 구간 수)
* 정해진 숫자 범위 안에서 균등하게 구간을 나눌 때
* 분류분석할 때 기준으로 쓸 수 있음

In [60]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [62]:
np.linspace(0, 1, 7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

### .sort()  /  sorted() : 정렬

In [3]:
f = np.array([5,7,11,1,3,2,54,0,0.5,68])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0. ,  0.5, 68. ])

In [6]:
# axis 속성에 따라 정렬 다르게 할 수 있음
np.sort(f)

array([ 0. ,  0.5,  1. ,  2. ,  3. ,  5. ,  7. , 11. , 54. , 68. ])

In [66]:
f.sort() # 바로 재할당
f

array([ 0. ,  0.5,  1. ,  2. ,  3. ,  5. ,  7. , 11. , 54. , 68. ])

In [70]:
np.array(sorted(np.array([5,7,11,1,3,2,54,0,0.5,68]), reverse=True))

array([68. , 54. , 11. ,  7. ,  5. ,  3. ,  2. ,  1. ,  0.5,  0. ])

### argsort()
* 자료 중 값이 작은 것에서 큰 순으로 원래 인덱스 출력
* 추천 시스템 (ex. 영화, 금융 상품)

In [71]:
g = np.array([5,0.5,-7,42,10,0])
print(g)

[ 5.   0.5 -7.  42.  10.   0. ]


In [74]:
idx = g.argsort()
idx

array([2, 5, 1, 0, 4, 3])

In [75]:
g[idx]

array([-7. ,  0. ,  0.5,  5. , 10. , 42. ])

In [76]:
g[idx][::-1]

array([42. , 10. ,  5. ,  0.5,  0. , -7. ])

### np.where(조건, 참, 거짓) : 3항 연산

In [8]:
num = np.arange(1,11)
num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.where(num % 2 == 0, '짝수', '홀수')

array(['홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수', '홀수', '짝수'],
      dtype='<U2')

## 배열 합치기 np.concatenate()

In [10]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a, a.shape)
print(b, b.shape)

[[1 2]
 [3 4]] (2, 2)
[[5 6]
 [7 8]] (2, 2)


### np.concatenate((a,b))
* 합치는 기본 방향은 axis=0 (행추가)
* axis=1 (열추가)
* 합치는 방향의 모양이 일치하지 않으면 합치기 불가

In [11]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [12]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## 전치행렬
* 행과 열을 바꿈
* .T
* .trabsoise()

In [13]:
np.concatenate((a,b), axis=1).T

array([[1, 3],
       [2, 4],
       [5, 7],
       [6, 8]])

In [14]:
np.concatenate((a,b), axis=1).transpose()

array([[1, 3],
       [2, 4],
       [5, 7],
       [6, 8]])

## 브로드 캐스팅
* 벡터와 스칼라 혹은 matrix와 벡터를 연살할 때 자동으로 행렬 크키를 맞춰 주는 것

In [16]:
a = np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
a + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
b = np.array([10,20,30,40,50])
b

array([10, 20, 30, 40, 50])

In [20]:
a + b

array([[11, 22, 33, 44, 55],
       [16, 27, 38, 49, 60],
       [21, 32, 43, 54, 65]])